const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID';
const ALERT_SUCCESS = 'ALERT_SUCCESS';
const ALERT_ERROR = 'ALERT_ERROR';
const ALERT_CLEAR = 'ALERT_CLEAR';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const GET_SESSIONS_REQUEST = 'GET_SESSIONS_REQUEST';
const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
const GET_SESSIONS_FAILURE = 'GET_SESSIONS_FAILURE';
const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';
const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
const GET_APPOINTMENTS_FAILURE = 'GET_APPOINTMENTS_FAILURE';
const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
const GET_APPOINTMENTS_REQUEST = 'GET_APPOINTMENTS_REQUEST';


export { GET_APPOINTMENTS_FAILURE, GET_APPOINTMENTS_SUCCESS, GET_APPOINTMENTS_REQUEST, CREATE_APPOINTMENT_REQUEST, CREATE_APPOINTMENT_SUCCESS, CREATE_APPOINTMENT_FAILURE, GET_SESSIONS_FAILURE, GET_SESSIONS_REQUEST, GET_SESSIONS_SUCCESS, LOGOUT_SUCCESS, LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILURE, SIGNUP_REQUEST, SIGNUP_SUCCESS, SIGNUP_FAILURE, SET_CURRENT_USER_ID, ALERT_SUCCESS, ALERT_ERROR, ALERT_CLEAR };